services:
  - type: web
    name: spring-boot-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        value: postgres://myuser:secret@postgres:5432/mydatabase
    healthCheckPath: /
    autoDeploy: true