package com.doorway.Model;

public enum ExcellencePrinciple {
    IMPACTFUL_DELIVERY,
    WISE_INSIGHTS,
    SIMPLIFIED_INNOVATION,
    OUTSTANDING_MENTORSHIP,
    OBSESSIVE_AMBITION,
    CUSTOMER_DEDICATION,
    DEEP_OWNERSHIP,
    PERFECTIONIST_MASTERY,
    EMPATHIC_INCLUSION,
    CONFIDENT_MODESTY,
}